[SSL] Add ability to set verification flags
puma/puma pull request #2490
Opened 2020-11-23 14:51 UTC by Bonias

### Description

Add ability to set OpenSSL verification flags (https://www.openssl.org/docs/manmaster/man3/X509_VERIFY_PARAM_set_hostflags.html#VERIFICATION-FLAGS).

We had a need to set `X509_V_FLAG_PARTIAL_CHAIN` flag. Most major TLS libraries behaves like this by default but not OpenSSL (https://github.com/openssl/openssl/issues/7871). Adding ability to set any verification flag allows us to set `X509_V_FLAG_PARTIAL_CHAIN` flag. I think it may be useful for other too.

I implemented this for MRI only as I don't know how to do this for JRuby (and if this is even required?).

### Your checklist for this pull request

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added an entry to [History.md](../blob/master/History.md) if this PR fixes a bug or adds a feature. If it doesn't need an entry to HISTORY.md, I have added `[changelog skip]` or `[ci skip]` to the pull request title.
- [x] I have added appropriate tests if this PR fixes a bug or adds a feature.
- [ ] (almost) My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [x] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

2020-11-23 15:18 UTC, dentarg commented on README.md
> +#### Controlling Open SSL Verification Flags
```suggestion
#### Controlling OpenSSL Verification Flags
```

2020-11-23 15:50 UTC, MSP-Greg requested changes

2020-11-23 15:50 UTC, MSP-Greg commented on lib/puma/dsl.rb
> +      additions = +''
Given that Puma is currently supporting Ruby 2.2:

```suggestion
      additions = ''.dup
```

2020-11-24 15:47 UTC, MSP-Greg approved these changes

2020-11-24 16:32 UTC, MSP-Greg commented
@Bonias

Not that familiar with these flags, or how and when they may be set.  In `mini_ssl.c`, might it be better to change:
```
    param = X509_VERIFY_PARAM_new();
```

to something like:
```
    param = SSL_CTX_get0_param(ctx);
```

2020-11-26 11:06 UTC, Bonias commented
Thanks @MSP-Greg! I changed it to `SSL_CTX_get0_param`

2020-12-03 01:03 UTC, MSP-Greg commented
@Bonias

Well, I found out what one can't do with git...

I rebased this, adjusted dsl.rb, then hit a compile issue, fixed that, then decided that, rather than repeating `&verification_flags=` in the query string, that concatenating the strings would be a lot easier to look at...

I don't know what you think, but the patch is at:

https://github.com/MSP-Greg/puma/commit/4d063d982c5.patch

If you rebase, then replace the PR commit with the above, it should be good to merge, and CI did pass...

2020-12-07 23:13 UTC, Bonias commented
I rebased this. I also updated README and History files. I hope all is good now.

2020-12-07 23:21 UTC, merged

2020-12-07 23:25 UTC, MSP-Greg commented
@Bonias

Thank you.  Sorry for the trouble, the changes I made to DSL got merged first, so this got messy.

The DSL changes allow access to the ssl bind string, which makes CI a bit easier...