Add debug to worker timeout and startup. Closes #2528
puma/puma pull request #2559
Opened 2021-02-20 21:03 UTC by ylecuyer

### Description
Fixes #2528 adding the reason for worker timeout and the startup time when worker boots

### Your checklist for this pull request

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added an entry to [History.md](../blob/master/History.md) if this PR fixes a bug or adds a feature. If it doesn't need an entry to HISTORY.md, I have added `[changelog skip]` or `[ci skip]` to the pull request title.
- [x] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

2021-02-20 21:05 UTC, ylecuyer commented on test/helpers/integration.rb
> +    assert(system(*args, out: File::NULL, err: File::NULL))
Removed err as bundler keeps on complaining my version is not the same as the one in the `Gemfile.lock`
I also added an assert to make sure the command exited with success

2021-02-20 22:29 UTC, dentarg commented on History.md
> +* Minor
```suggestion
* Features
```

2021-02-20 22:33 UTC, dentarg approved these changes
LGTM

2021-02-20 22:39 UTC, dentarg requested changes
Looks like failing tests needs to be addressed

2021-02-21 11:58 UTC, ylecuyer commented
> Looks like failing tests needs to be addressed

I have fixed the ruby < 2.4 versions. Sadly I can't test locally as I don't have the right openssl version to compile the old rubies. Let's see if the CI is happy this time ;)

2021-03-06 14:31 UTC, MSP-Greg commented
CI is fine, current CI has intermittent failures/errors for all platforms/versions.  See:

https://github.com/MSP-Greg/puma/actions/runs/626438062, failures here passed, ubuntu-18.04 2.6 failed.

@cjlarose - given #2528, if you have time to review...

2021-03-06 16:19 UTC, dentarg commented on lib/puma/cluster.rb
> +                  log "- Worker #{w.index} (PID: #{pid}) booted in #{w.uptime.truncate(*(RUBY_VERSION >= "2.4." ? [2] : []))}s, phase: #{w.phase}"
```suggestion
                  log "- Worker #{w.index} (PID: #{pid}) booted in #{w.uptime.round(2)}s, phase: #{w.phase}"
```

Should also get us decimals when using Ruby < 2.4

2021-03-06 16:20 UTC, dentarg commented
> Sadly I can't test locally as I don't have the right openssl version to compile the old rubies

If you can use Docker, it is as simple as `docker run --rm -it ruby:2.2` (it will start `irb` as default)

2021-03-08 18:37 UTC, cjlarose commented
> @cjlarose - given #2528, if you have time to review...

Oh man I forgot I wrote that issue. I'll do some local testing on this, but on the surface, this looks great!

2021-03-11 06:00 UTC, cjlarose approved these changes
Awesome work. Thanks for doing this!

2021-03-11 13:14 UTC, dentarg approved these changes
I assume the CI failures are not related

(18.04 2.7 flaky `test_hot_restart_does_not_drop_connections` and Win 2019 2.3 `SignalException: SIGSEGV`, flake too?)

2021-03-11 17:17 UTC, merged