minissl.c - Use Random.bytes if available
puma/puma pull request #2642
Opened 2021-06-11 22:41 UTC by MSP-Greg

### Description

PR #2633 throws deprecation warnings in Ruby 3.  Fix by using `Random.bytes` when available.

### Your checklist for this pull request
- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [ ] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

2021-06-12 10:17 UTC, eregon approved these changes
Looks good!

2021-06-16 14:16 UTC, MSP-Greg commented
I looked at this one more time, and thought maybe the below was a little clearer.  Note that this code is only called on Puma start/restart, once for each ssl binder/listener.
```c
// Random.bytes available in Ruby 2.5 and later, Random::DEFAULT deprecated in 3.0
#ifdef HAVE_RANDOM_BYTES
  bytes_func = rb_cRandom;
#else
  bytes_func = rb_const_get(rb_cRandom, rb_intern_const("DEFAULT"));
#endif
  session_id_bytes = rb_funcall(bytes_func, rb_intern_const("bytes"),
                                1, ULL2NUM(SSL_MAX_SSL_SESSION_ID_LENGTH));
```
If anyone has objections, please let me know, otherwise I'll change.  I also added the comment to `extconf.rb`, and output a line like `checking for Random.bytes... <yes/no>`...

2021-06-16 14:37 UTC, onlined commented
I like the approach, but I don't like the name `bytes_func`. The name suggests that the object is a method or function, but it's not. A name like `object_with_bytes_method` could be better, or you can do this without a variable:
```ruby
  // Random.bytes available in Ruby 2.5 and later, Random::DEFAULT deprecated in 3.0
  session_id_bytes = rb_funcall(
#ifdef HAVE_RANDOM_BYTES
    rb_cRandom,
#else
    rb_const_get(rb_cRandom, rb_intern_const("DEFAULT")),
#endif
    bytes_func, 
    rb_intern_const("bytes"),
    1, ULL2NUM(SSL_MAX_SSL_SESSION_ID_LENGTH)
  );
```

2021-06-16 16:21 UTC, onlined requested changes

2021-06-16 16:21 UTC, onlined commented on ext/puma_http11/mini_ssl.c
> +// Random.bytes available in Ruby 2.5 and later, Random::DEFAULT deprecated in 3.0
Can you align this comment with the line below by indenting one level?

2021-06-16 17:05 UTC, onlined approved these changes

2021-06-16 17:33 UTC, merged