WIP: Github Actions. Add rubocop and running condition for the ragel pipeline.
puma/puma pull request #2872
Opened 2022-05-06 16:22 UTC by alexeevit

…ndle install in ruby tests

### Description
Please describe your pull request. Thank you for contributing! You're the best.

### Your checklist for this pull request

- [ ] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [ ] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [ ] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed, including Rubocop.

2022-05-06 22:48 UTC, MSP-Greg commented
@alexeevit

Along with the above, MSP-Greg/setup-ruby-pkgs is now ruby/setup-ruby-pkgs

2022-05-07 18:35 UTC, alexeevit commented
@MSP-Greg yep, fixed it here and in the ruby tests as well.

I've checked the "paths" filter, works well: https://github.com/alexeevit/puma/pull/2

2022-05-07 18:57 UTC, alexeevit commented
I also found that we have a few of flaky specs. Should I create issues about them?

2022-05-07 19:24 UTC, MSP-Greg commented
> have a few flaky specs

I assume you mean intermittent test failures/errors?  If you find clear fixes for them, feel free to open a PR, but often they are timing related, and timing can be an issue with shared CI VM's.  Or, most are really intermittent, so it's hard to determine if one has really fixed them.

Conversely, if they really represent a failure in that Puma moves to a state that isn't accounted for, it's a problem.

Sorry, not the best answer.

Have you had a chance to look my comments above?

2022-05-07 19:31 UTC, alexeevit commented
> Have you had a chance to look my comments above?

I see only one comment about `ruby/ruby-setup`

> I assume you mean intermittent test failures/errors? If you find clear fixes for them, feel free to open a PR, but often they are timing related, and timing can be an issue with shared CI VM's. Or, most are really intermittent, so it's hard to determine if one has really fixed them.

> Conversely, if they really represent a failure in that Puma moves to a state that isn't accounted for, it's a problem.

> Sorry, not the best answer.

It's a good answer. Yes, I meant intermttent test failures. I'm not sure, but it seems that we don't really care about them. I'd prefer to keep all cases under control. At least, I think it'd be a good idea to have an up-to-date list of all of them. Thus the community could help to investigate and fix them.

2022-05-07 19:41 UTC, MSP-Greg requested changes

2022-05-07 19:47 UTC, alexeevit commented on .github/workflows/ragel.yml
> +      - 'ext/**'
done

2022-05-07 19:47 UTC, alexeevit commented on .github/workflows/ragel.yml
> +    needs: rubocop
done

2022-05-07 20:28 UTC, MSP-Greg commented
> Have you had a chance to look my comments above?

Sorry, I forgot to click one button, I see you've seen them...

> it seems that we don't really care about them

Actually, there's been quite a few small changes trying to fix them.

> At least, I think it'd be a good idea to have an up-to-date list of all of them. Thus the community could help to investigate and fix them.

A list, or maybe add 'intermittent failure/error' to the assert/refute message.  Or both.  I've looked at a few of them, and they're difficult.  Often, one can never get them to fail locally...

2022-05-07 21:21 UTC, MSP-Greg commented
@alexeevit

Sorry, I should have clearer.  There were two instances of `- '.github/workflows/**'` in the ragel.yml file.  You changed one to `- '.github/workflows/ragel.yml'.  Can you change the other?  Otherwise, LGTM

2022-05-08 12:09 UTC, alexeevit commented
> @alexeevit
> 
> Sorry, I should have clearer. There were two instances of `- '.github/workflows/**'` in the ragel.yml file. You changed one to `- '.github/workflows/ragel.yml'. Can you change the other? Otherwise, LGTM

Oh sorry, I rushed. Fixed.

2022-05-08 12:13 UTC, alexeevit commented
> A list, or maybe add 'intermittent failure/error' to the assert/refute message. Or both.

Yep, this could be cool. I'd also add retries for such tests.

> I've looked at a few of them, and they're difficult. Often, one can never get them to fail locally...

Yeah, I see. But this list or tag could increase our awareness of them and we probably should check if they're just bad tests or there're floating bugs.

2022-05-08 13:26 UTC, MSP-Greg approved these changes

2022-05-08 14:02 UTC, MSP-Greg commented
Thanks for fixing that last item.

> add retries for such tests

We're already using minitest-retry, not sure if another retry mechanism is needed.

> this list or tag could increase our awareness of them

One problem with the above is that some of the failures seem to be dependent on the Ruby being used (version, 'MRI', platform, etc).  For instance, a failure tolerated on a Ruby head version maybe shouldn't be tolerated on a release version...

> check if they're just bad tests or there're floating bugs.

Hard to say.  Given that CI passes more than not, and also that failures are often just one job, it's messy.  One way to check things is to use the test seed value locally and see if the failure can be repo'd.  I haven't done it for a while, but when I did, the tests often passed.

2022-05-14 15:32 UTC, merged

2022-05-14 15:32 UTC, MSP-Greg commented
@alexeevit Thanks!