[Fix #3044] Set conditional config defaults after CLI options are parsed
puma/puma pull request #3297
Opened 2023-12-24 09:28 UTC by joshuay03

### Description

Closes https://github.com/puma/puma/issues/3044

`CLI` options are parsed during `CLI` initialisation, but after `Configuration` initialisation. This PR changes this so that the parse takes place during `Configuration` initialisation as well. This ensures that config defaults that are conditionally set during initialisation use all parsed options, which fixes the linked issue.

### Your checklist for this pull request

- [ ] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [ ] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [ ] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed, including Rubocop.

2023-12-24 09:51 UTC, joshuay03 commented on test/test_cli.rb
> -    cli.send(:setup_options)
I think these are unnecessary, options are set up when initialised.

2023-12-24 09:52 UTC, joshuay03 commented on test/test_cli.rb
> +    assert_equal true, config.options[:preload_app]
Before patch:
<img width="727" alt="Screenshot 2023-12-24 at 7 50 33 pm" src="https://github.com/puma/puma/assets/54629302/58ce6a77-e954-44cd-a5e3-508afe59d9a9">

2023-12-24 10:19 UTC, joshuay03 commented on test/test_config.rb
> +    assert_equal preload, conf.options.default_options[:preload_app]
Before patch:
<img width="860" alt="Screenshot 2023-12-24 at 8 19 44 pm" src="https://github.com/puma/puma/assets/54629302/c9e40935-7ce5-4c86-9c7f-c8aa38f1eefd">

2023-12-24 21:19 UTC, dentarg commented
Are the test failures related to (these) tests now using preloading (and that causes some problem)?

While https://github.com/puma/puma/issues/3044 is classed as a bug, it is quite the change in behaviour... so maybe the fix should be shipped in a major version?

2023-12-25 00:45 UTC, joshuay03 commented
> Are the test failures related to (these) tests now using preloading (and that causes some problem)?

I think the phased restart failures are because of [this clause](https://github.com/puma/puma/blob/83c5b32990e5c0ca5a61baa915e506c00308041f/lib/puma/cluster.rb#L221). I think we should just make it one of the conditions of defaulting `preload_app` to `true` considering that we give users the same advise for their config:

https://github.com/puma/puma/blob/83c5b32990e5c0ca5a61baa915e506c00308041f/README.md?plain=1#L139

https://github.com/puma/puma/blob/83c5b32990e5c0ca5a61baa915e506c00308041f/lib/puma/dsl.rb#L800-L801

> While #3044 is classed as a bug, it is quite the change in behaviour... so maybe the fix should be shipped in a major version?

I agree, and yes the issue was added to the `7.0.0` milestone.

2024-11-23 01:17 UTC, nateberkopec approved these changes

2024-11-27 21:41 UTC, nateberkopec requested changes, later dismissed
Test fails? 🤔

2024-12-01 07:13 UTC, joshuay03 commented
The last failure is related to https://github.com/puma/puma/pull/3557#discussion_r1864735186

I'm pretty sure we want `fork_worker` enabled for that test, and here I've also disabled preloading for consistency with the other tests since it's not compatible with phased restart. However, it seems that when you do both of those things, phased restarts slow down quite a bit, leading to test timeouts. Setting them individually however is completely fine. 

I'll have a go at looking into this in a separate PR.

2024-12-30 09:46 UTC, dentarg commented
So we're waiting for https://github.com/puma/puma/pull/3589 here

2025-02-11 21:37 UTC, joshuay03 commented
I've updated this to target https://github.com/puma/puma/pull/3616. Once that has been merged, this should go green after rebasing.

2025-08-02 03:07 UTC, joshuay03 commented
> I've updated this to target #3616. Once that has been merged, this should go green after rebasing.

Nvm, I've just patched those tests here. Now neither is dependant on the other and both should cleanly rebase after the other is merged.

2025-08-12 22:21 UTC, schneems commented
I'm not sure why but the UX is telling me that @nateberkopec requested changes even though I don't see the request (and I see an approval from him). All tests are now green. @nateberkopec can you merge in or re-iterate your concerns that seem to have been lost to the snads of time?

2025-08-12 23:26 UTC, joshuay03 commented
> I'm not sure why but the UX is telling me that @nateberkopec requested changes even though I don't see the request (and I see an approval from him). All tests are now green. @nateberkopec can you merge in or re-iterate your concerns that seem to have been lost to the snads of time?

It was because there was a test failure:

> Test fails? 🤔

Which has since been resolved:

> The last failure is related to [#3557 (comment)](https://github.com/puma/puma/pull/3557#discussion_r1864735186)
> 
> I'm pretty sure we want `fork_worker` enabled for that test, and here I've also disabled preloading for consistency with the other tests since it's not compatible with phased restart. However, enabling `fork_worker` seems to slow the test down enough for it to time out.
> 
> **Edit:** Resolved in #3589

2025-08-20 18:49 UTC, MSP-Greg commented
> Now neither is dependant on the other and both should cleanly rebase

Re #3616, just checking if the above is still true.  I haven't looked much at this one, but @nateberkopec went thru it...

2025-08-20 22:53 UTC, joshuay03 commented
> > Now neither is dependant on the other and both should cleanly rebase
> 
> Re #3616, just checking if the above is still true. I haven't looked much at this one, but @nateberkopec went thru it...

Probably not with my recent changes. Once #3616 has been merged, I'll come and clean this up. I might have to update the `#clamp` [changes](https://github.com/puma/puma/pull/3297/files#diff-2dc4e3e83be7fd97cebc482ae07d6a8216944003de82458783fb00b5ae9524c8R260-R265) and I can remove some unnecessary `#load` [calls](https://github.com/puma/puma/pull/3297/files#diff-f8a5111e8509bf1e3c382deae1d40eb8640626bd81cd5066577d3082d8e0a7dfR763-R764) in tests.

FWIW, if I had to pick a PR (of mine) that definitely should go out with v7, it would be this one. I've worked with 2 monoliths now where they almost set `WEB_CONCURRENCY` without realising they would be enabling preloading, thinking that when they bumped to v5, preloading was already enabled. It's quite confusing default behaviour. We should also include a big warning next to this PR in the changelog that bumping to v7 would enable preloading by default if in cluster mode, regardless of whether the configuration is done via DSL or env var, and that people should set `preload_app!(false)` to maintain current behaviour—highly advised because you need to be careful when enabling this if you have threads spawned on boot.

cc @schneems

2025-08-25 20:45 UTC, schneems commented
#3616 is merged. Can you rebase on master/main (thanks).

2025-08-25 22:48 UTC, MSP-Greg commented
Cancel 'older' CI tests?

2025-08-25 22:51 UTC, joshuay03 commented
> Cancel 'older' CI tests?

Yes please, thank you!

2025-08-26 00:03 UTC, joshuay03 commented
> #3616 is merged. Can you rebase on master/main (thanks).

Done 👍🏽

2025-08-26 00:23 UTC, merged