Move fork_worker to parent thread
puma/puma pull request #3504
Opened 2024-09-27 18:49 UTC by chjasonwu

### Description
Please describe your pull request. Thank you for contributing! You're the best.

### Your checklist for this pull request

- [ ] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [ ] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [ ] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed, including Rubocop.

2024-10-02 23:38 UTC, chjasonwu commented
@dentarg @MSP-Greg I kinda can't tell if these tests are failing due to regression or just being flaky, since retry in my github actions seems to yield different results. https://github.com/chjasonwu/puma/actions/runs/11151795195

2024-10-02 23:57 UTC, MSP-Greg commented
@chjasonwu

First of all, I haven't had time to review this PR.

But, the current Puma test suite may have intermittent failures, I'll re-run the failing tests.

2024-10-04 05:46 UTC, dentarg commented
Marked this as something for Puma v7 as it sounds like a change in behaviour – feel free to share any thoughts on that

2024-10-17 23:42 UTC, chjasonwu commented
@MSP-Greg @dentarg @wjordan 

I plan to move child process forking back to the same thread handling requests. Any guidance or feedback would be greatly appreciated.

2024-10-24 23:16 UTC, chjasonwu commented
Previous failure is related to this https://github.com/puma/puma/pull/3532. I'll have to rebase.

2024-10-25 18:46 UTC, chjasonwu commented
@MSP-Greg @dentarg @wjordan 

I hadn’t heard back, so I just wanted to follow up. Any feedback you could share would be really appreciated.

2025-01-10 10:49 UTC, dentarg commented
Maybe @toregeschliman can review this?

2025-01-14 23:35 UTC, toregeschliman reviewed
I like this in principle (keeping `Thread.main` as `Thread.main` solves a set of forking problems we've run into with `fork_worker`) but I'm not clear on the purpose of the new locking and I always prefer alternatives to avoid the common `Thread.new` solution for signal handlers. If we're going to go that way we might as well just stop using the Queue since it's really just a threadsafe tool that's usable in signal handler context.

2025-01-14 23:35 UTC, toregeschliman commented on lib/puma/cluster/worker.rb
> +        mutex = Mutex.new
I'm not clear on what this buys us; nothing about the new state in the queue seems to require synchronizing around this and it messes up the signal trap hooks pretty badly. Which race condition were you worried about here?

2025-01-14 23:35 UTC, toregeschliman commented on lib/puma/cluster/worker.rb
> +        restart_server = Queue.new << Puma::Const::WorkerCmd::RESTART << Puma::Const::WorkerCmd::STOPPED
We should probably rename the queue if it's no longer just booleans

2025-01-14 23:35 UTC, toregeschliman commented on lib/puma/cluster/worker.rb
> +                restart_server << "#{Puma::Const::WorkerCmd::SPAWN}#{idx}"
We should definitely pass the idx state somewhere else, this is allocating multiple strings every loop for objects that are otherwise interned/intern-able.

2025-01-15 01:40 UTC, toregeschliman commented on lib/puma/cluster/worker.rb
> +        mutex = Mutex.new
There's probably a narrower fix for CI, given the unlikelihood of the race condition in the real world; most setups are likely going to send a second signal if it doesn't terminate in time, and nobody restarts worker zero as frequently or quickly as tests do (ideally). As mentioned above if we think we need the mutex, we should change the restart_server queue to a simpler state machine, but I think the easier fix is to continue to avoid the mutex and add a second TERM to the specs.

2025-01-15 02:01 UTC, toregeschliman commented
This is close but is also likely to be superseded by upcoming work to convert worker-0 to a non-serving parent process (or "mold"), which I'm hoping to start work on in the next week. I won't block on that certainly since it's not yet in progress.

2025-01-31 07:40 UTC, nateberkopec commented
@toregeschliman I assume the idea there is that worker-0 will be killed once the next child worker is running, right?

I'm not sure that this PR really is v7 or a breaking change. I prefer to merge something like this rather than wait for a PR which is not yet opened.

2025-01-31 07:42 UTC, nateberkopec requested changes
I'm OK with merging this if @toregeschliman's comments are addressed.

2025-01-31 09:56 UTC, joshuay03 commented on lib/puma/cluster.rb
> +        log "Spawned worker: #{pid}, phase: #{@phase}"
There's already a log line on worker boot: https://github.com/chjasonwu/puma/blob/38724d4666aac0980ebd0779fd33ddef1c3ec468/lib/puma/cluster.rb#L477

Do we need one for spawn as well? If we are adding it, should the formatting match the boot log to include the indentation and index?
```suggestion
        log "- Worker #{idx} (PID: #{pid}) spawned, phase: #{@phase}"
```

<br>

IMO this does seem like more of a debug-only log, but that's for the maintainers to decide.

2025-01-31 09:56 UTC, joshuay03 commented on test/test_integration_cluster.rb
> +    cli_server "-w 2 test/rackup/hello.ru", puma_debug: true, config: <<~CONFIG
Need to remove this before merge.

2025-02-13 14:34 UTC, toregeschliman commented
@nateberkopec started work at https://github.com/puma/puma/pull/3619/files on this; rough idea is just for worker zero to stop handling requests whenever it's asked to do its first refork (after initialization) and move to a fork_worker loop on the main thread listening for further signals; this reduces the risk of restarting for OOM, timeouts, or other things that can interrupt it while handling fork_worker state. I plan to extend it eventually with generational molding, which could include terminating legacy molds, but we'll still be keeping the active mold live to refork any workers >= 1 that terminate for other reasons.

When it's done I want to test it for a while internally before taking it out of draft so I still don't consider it blocking on this PR.

2025-05-28 23:41 UTC, chjasonwu commented
@nateberkopec, I'm closing this and will leveraging Tore's mold_worker instead. https://github.com/puma/puma/issues/3596.

The mold_worker implementation will not spawn a different thread for worker spawning, which will comply with gRPC. It's probably a better way to moving forward, instead of me patching this again instead.

2025-05-29 18:57 UTC, closed without merging